#:schema node_modules/wrangler/config-schema.json
name = "email-worker"
main = "src/index.ts"
compatibility_date = "2024-07-25"
compatibility_flags = ["nodejs_compat"]

[vars]
WEBHOOK_URL = "https://webhook.site/00917f5a-2a0a-49a7-bbd4-39172cbcc9eb"